### ISSUE TITLE
i'm gonna rename this to `various-js` or `various` or `random` or `stuff` or something.

### ISSUE THREAD

**Issue by paperdave** [paperdave/various#5]
maybe even `something` or something.

i dont like the `-web` suffix. since i just threw logger together, and that DOES not run in the web.

**Comment by Clembs** [comment]
i'd suggest `utilikit` since it's kind of a kit of JS utilities, but `various` sounds fun too

**Comment by paperdave** [comment]
it wouldn't be wrong to call it all utilities but it doesn't feel right to me.
